### ISSUE TITLE
Demo link error 404

### ISSUE THREAD

**Issue by newbie2005** [jacobmischka/vue-flatpickr#3]
https://jrainlau.github.io/vue-flatpickr/  Error 404

**Comment by jacobmischka** [comment]
Yeah, I haven't updated the readme since forking. One of these days I'll try to get around to it, thanks for the reminder.

**Comment by jacobmischka** [comment]
I'm currently not hosting a demo anywhere, so I removed it from the readme. The readme in general needs some work right now but I'm going to close this as I don't plan on hosting another demo. Definitely welcome to accept a contribution that adds it though!
